set(OBSE_VERSION_MAJOR 0)
set(OBSE_VERSION_MINOR 1)
set(OBSE_VERSION_PATCH 0)

set(RUNTIME_VERSION_MAJOR 0)
set(RUNTIME_VERSION_MINOR 411)
set(RUNTIME_VERSION_PATCH 140)
set(RUNTIME_VERSION_TYPE 0)

math(
	EXPR
	RUNTIME_VERSION_PACKED
	"((${RUNTIME_VERSION_MAJOR} & 0xF) << 28) | ((${RUNTIME_VERSION_MINOR} & 0xFFF) << 16) | ((${RUNTIME_VERSION_PATCH} & 0xFFF) << 4) | (${RUNTIME_VERSION_TYPE} & 0xF)"
	OUTPUT_FORMAT
		HEXADECIMAL
)
